


GET http://localhost:8085/customers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzQ5MzI3NTM0LCJpYXQiOjE3NDkzMjY5MzQsInNjb3BlIjoiVVNFUiJ9.SYGmvu9L11eaXroB1orx8u3sgfYtItZxqbiT83KRAYchtLre2uubsOUQx9r4GHu23E5Lwa42J54URQnRWQSthg

###

GET http://localhost:8085/auth/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzQ5MzI3NTM0LCJpYXQiOjE3NDkzMjY5MzQsInNjb3BlIjoiVVNFUiJ9.SYGmvu9L11eaXroB1orx8u3sgfYtItZxqbiT83KRAYchtLre2uubsOUQx9r4GHu23E5Lwa42J54URQnRWQSthg

###

POST http://localhost:8085/auth/login
Content-Type: application/x-www-form-urlencoded

username=user&password=12345
