


GET http://localhost:8085/accounts/902eb9cb-49e1-42ee-b4d3-658394dafa35/pageOperations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTQwNTQyNCwiaWF0IjoxNzQ5NDA0ODI0LCJzY29wZSI6IkFETUlOIFVTRVIifQ.j-tOW-Ka7MH1qiSPLOlGwpb3LxWDOtCej-hbwqkxj8Qq4ojnHjoPExHEskb8xuKjTI5cDvn1e5pEp-1ZVeJcgw

###

DELETE http://localhost:8085/api/users/wassap
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTM4NTgyMSwiaWF0IjoxNzQ5Mzg1MjIxLCJzY29wZSI6IkFETUlOIFVTRVIifQ.6gJn50nrSVxKMFIL06aEvdJy1Vk7OjZQT20oBRwg0ffuOxFxBh4Qe2UeJu3d6NHF2tjFcZfTxJ8YQxR8wPTVgQ

###

POST http://localhost:8085/api/users/newuser/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTQwNTQyNCwiaWF0IjoxNzQ5NDA0ODI0LCJzY29wZSI6IkFETUlOIFVTRVIifQ.j-tOW-Ka7MH1qiSPLOlGwpb3LxWDOtCej-hbwqkxj8Qq4ojnHjoPExHEskb8xuKjTI5cDvn1e5pEp-1ZVeJcgw

{
  "newPassword": "123456"
}


###

POST http://localhost:8085/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTQwNTQyNCwiaWF0IjoxNzQ5NDA0ODI0LCJzY29wZSI6IkFETUlOIFVTRVIifQ.j-tOW-Ka7MH1qiSPLOlGwpb3LxWDOtCej-hbwqkxj8Qq4ojnHjoPExHEskb8xuKjTI5cDvn1e5pEp-1ZVeJcgw

{
  "username": "newuser",
  "password": "password123",
  "roles": ["USER"]
}


###

GET http://localhost:8085/api/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTQwNTQyNCwiaWF0IjoxNzQ5NDA0ODI0LCJzY29wZSI6IkFETUlOIFVTRVIifQ.j-tOW-Ka7MH1qiSPLOlGwpb3LxWDOtCej-hbwqkxj8Qq4ojnHjoPExHEskb8xuKjTI5cDvn1e5pEp-1ZVeJcgw

###

POST http://localhost:8085/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=12345

###
GET http://localhost:8085/api/dashboard/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTQwNTQyNCwiaWF0IjoxNzQ5NDA0ODI0LCJzY29wZSI6IkFETUlOIFVTRVIifQ.j-tOW-Ka7MH1qiSPLOlGwpb3LxWDOtCej-hbwqkxj8Qq4ojnHjoPExHEskb8xuKjTI5cDvn1e5pEp-1ZVeJcgw

###
GET http://localhost:8085/api/dashboard/recent-transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTQwNTQyNCwiaWF0IjoxNzQ5NDA0ODI0LCJzY29wZSI6IkFETUlOIFVTRVIifQ.j-tOW-Ka7MH1qiSPLOlGwpb3LxWDOtCej-hbwqkxj8Qq4ojnHjoPExHEskb8xuKjTI5cDvn1e5pEp-1ZVeJcgw

###

GET http://localhost:8085/api/dashboard/charts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTQwNTQyNCwiaWF0IjoxNzQ5NDA0ODI0LCJzY29wZSI6IkFETUlOIFVTRVIifQ.j-tOW-Ka7MH1qiSPLOlGwpb3LxWDOtCej-hbwqkxj8Qq4ojnHjoPExHEskb8xuKjTI5cDvn1e5pEp-1ZVeJcgw